version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    groups:
      npm-development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    allow:
      - dependency-name: actions/checkout
      - dependency-name: actions/setup-node
      - dependency-name: actions/upload-pages-artifact
      - dependency-name: actions/deploy-pages
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
